spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddi-auto: update

  datasource:
    url: jdbc:postgresql://localhost:5432/project
    username: project
    password: project
